title: James Posse Hunt
email: jamesjordanpo@gmail.com
description: >
  Blog about my attempt to get back into tech. Also a portfolio.
baseurl: "" 
url: "https://jamespossehunt.github.io"  # optional
github_username: JamesPosseHunt

markdown: kramdown
theme: minima
permalink: pretty

plugins:
  - jekyll-feed
